### ISSUE TITLE
Better replacement for :off: newline

### ISSUE THREAD

**Issue by dzucconi** [dzucconi/emojify#9]
This PR: https://github.com/dzucconi/emojify/pull/1 prepends everything with `:off:\n` which is for the benefit of users with avatars turned off.

Slack does some craftiness where if the first line is pretty much any kind of whitespace they strip it.

`:off:` is just a white square uploaded as a custom emoji. So obviously if you don't have that emoji specified you'll see the text `:off:`.

Open to sneaky suggestions to get around this.

**Comment by dblock** [comment]
Why do we even have this?

**Comment by dzucconi** [comment]
Yeah, I think we should drop it.

@mzikherman uses the compact layout that has avatars turned off; in that case the first row is always misaligned because your username pushes it over.

But who doesn't like avatars?

**Comment by mzikherman** [comment]
The emojify slackbot doesn't need this :+1: 

This was just useful for the web UI that generated the string you could copy/paste pre-Slack integration. For that it was nice to start off with a custom `:off:` to make sure there was no whitespace issues, so the Slackbot response doesn't need it.
